<a href="https://colab.research.google.com/github/Hamilton09/tareas/blob/main/Cuaderno_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create an array with random values between 1 and 10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(3, 4))

# Print the random array
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiply numbers')
print(a*b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[2 7 7 2]
 [7 4 4 9]
 [3 7 9 7]]
[[ 9  1 10  2]
 [ 6  3  1 10]
 [ 2  1  4  5]]
(3, 4)
(3, 4)
adding numbers
[[11  8 17  4]
 [13  7  5 19]
 [ 5  8 13 12]]
substracting numbers
[[-7  6 -3  0]
 [ 1  1  3 -1]
 [ 1  6  5  2]]
multiply numbers
[[18  7 70  4]
 [42 12  4 90]
 [ 6  7 36 35]]
[[11  8 17  4]
 [13  7  5 19]
 [ 5  8 13 12]]
[[18  7 70  4]
 [42 12  4 90]
 [ 6  7 36 35]]
[[0.22222222 7.         0.7        1.        ]
 [1.16666667 1.33333333 4.         0.9       ]
 [1.5        7.         2.25       1.4       ]]


In [2]:
a = np.random.randint(1, 11, size=(2, 3))
b = np.random.randint(1, 11, size=(3, 4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))
print(a.shape)

[[ 4  7 10]
 [ 8  5  9]]
[[ 3  7  7  6]
 [ 4  4  1  2]
 [10  6  7  3]]
[[140 116 105  68]
 [134 130 124  85]]
[[140 116 105  68]
 [134 130 124  85]]
(2, 3)


In [3]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[ 5  9]
 [ 9 10]]
[[ 5  9]
 [ 9 10]]


In [4]:
a = np.random.randint(1, 11, size=(4,3))
b = np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('---------------')
print(c)

(4, 3)
(3,)
[[ 2  6  1]
 [ 8  5  7]
 [ 4  2 10]
 [10  8  4]]
[1 0 2]
(4, 3)
---------------
[[2 7 7]
 [2 7 4]
 [4 9 3]
 [7 9 7]]


In [5]:
for i in range(4):
  c[i,:]=a[i,:]+b

  print(a)
  print(b)
  print(c)

  c=a+b
  print(c)

[[ 2  6  1]
 [ 8  5  7]
 [ 4  2 10]
 [10  8  4]]
[1 0 2]
[[3 6 3]
 [2 7 4]
 [4 9 3]
 [7 9 7]]
[[ 3  6  3]
 [ 9  5  9]
 [ 5  2 12]
 [11  8  6]]
[[ 2  6  1]
 [ 8  5  7]
 [ 4  2 10]
 [10  8  4]]
[1 0 2]
[[ 3  6  3]
 [ 9  5  9]
 [ 5  2 12]
 [11  8  6]]
[[ 3  6  3]
 [ 9  5  9]
 [ 5  2 12]
 [11  8  6]]
[[ 2  6  1]
 [ 8  5  7]
 [ 4  2 10]
 [10  8  4]]
[1 0 2]
[[ 3  6  3]
 [ 9  5  9]
 [ 5  2 12]
 [11  8  6]]
[[ 3  6  3]
 [ 9  5  9]
 [ 5  2 12]
 [11  8  6]]
[[ 2  6  1]
 [ 8  5  7]
 [ 4  2 10]
 [10  8  4]]
[1 0 2]
[[ 3  6  3]
 [ 9  5  9]
 [ 5  2 12]
 [11  8  6]]
[[ 3  6  3]
 [ 9  5  9]
 [ 5  2 12]
 [11  8  6]]


In [6]:
a=np.array([1,2,3])

print(a)
tmp=np.tile(a,(6,1))
print(tmp)


[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
a=np.random.randint(0,10, size=(6,6))
print(a)
aux=np.mean(a)
print(aux)
print(a.mean(axis=1))


[[7 5 7 4 3 7]
 [1 7 0 7 0 0]
 [9 6 7 0 2 7]
 [5 2 8 8 5 9]
 [6 0 3 2 3 2]
 [0 7 5 1 2 7]]
4.277777777777778
[5.5        2.5        5.16666667 6.16666667 2.66666667 3.66666667]
