<a href="https://colab.research.google.com/github/Hamilton09/tareas/blob/main/Cuaderno_Actividad_Asicrona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import numpy as np and see the version

# your code here
#pass
import numpy as np

In [2]:
# Create a 1D array of numbers from 0 to 9
# your code here
#pass
a = np.random.randint(0,9, size=(1,9))
print (a)

[[3 2 4 0 4 1 4 4 8]]


In [3]:
# Create random vector of size 10 and replace the maximum value by 0
#pass
vector= np.random.randint(0,101, size=10)
print("Vector original:")
print(vector)
indice_maximo=np.argmax(vector)
vector[indice_maximo] = 0
print("Vector con el máximo valor reemplazado por O:")
print(vector)

Vector original:
[42 25 99 99 91 69 80 28 24 28]
Vector con el máximo valor reemplazado por O:
[42 25  0 99 91 69 80 28 24 28]


In [4]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
#pass
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
number=arr[1,2]
print("Numero o from the array:", number)

Numero o from the array: 8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
#pass
arr=np.array([1,2,3,4,5,6,7])
numer=arr[2:5]
print("numero impreso:", numer)

numero impreso: [3 4 5]


In [6]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
#pass
arr=np.array([1,2,3,4,5,6,7])
numer=arr[-4:]
print("numero impreso:", numer)

numero impreso: [4 5 6 7]


In [7]:
# Create a 3×3 numpy array of all True’s
# your code here
#pass
matriz= np.ones((3,3), dtype=bool)
print("matriz 3*3")
print(matriz)

matriz 3*3
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Extract all odd numbers from arr
# your code here
#pass
arr = np.array([1,2,3,4,5,6,7,8,9])
odd_number=arr[arr % 2 !=0]
print("numeros impares:", odd_number)

numeros impares: [1 3 5 7 9]


In [9]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
#pass
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Reverse a vector (first element becomes last)
#pass
vector=np.array([1,2,3,4,5])
vector_revertido = vector[::-1]
print(vector)

[1 2 3 4 5]


In [11]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
#pass
matriz = np.random.randint(0,101, size=(10,10))
print("Matriz de  10*10 valores enteros aleatorios:")
print(matriz)

valor_minimo=np.min(matriz)
valor_maximo=np.max(matriz)
print("Valor nínimo en la matriz:", valor_minimo)
print("Valor máximo en la matriz:", valor_maximo)

Matriz de  10*10 valores enteros aleatorios:
[[ 33  81  14  10  45   2  63  97  12  81]
 [  8  23  18  94  44   9  88  26  38  14]
 [100  18  45  18  25  84  71  60  53  72]
 [ 87  64  74  92  18  57  31  99  96  26]
 [ 52  62   1  73  74  38  63  98  89  39]
 [ 30  54  82  35  55  18  83  86  83  54]
 [ 31  72  43   8  51  96  41  70  50  58]
 [ 80  72  35  98  44  43  64  60  27  98]
 [ 70  93  97  71  69  72  61  19  15  57]
 [ 63  59  96  73  81  15  67  31  31  59]]
Valor nínimo en la matriz: 1
Valor máximo en la matriz: 100


In [12]:
# Create a 3x3x3 array with random values
#pass
matriz_tridimensional = np.random.random((3, 3, 3))
print("Matriz tridimensional 3x3x3 con valores aleatorios:")
print(matriz_tridimensional)

Matriz tridimensional 3x3x3 con valores aleatorios:
[[[0.68722359 0.05831956 0.09425655]
  [0.03418933 0.69320232 0.62127369]
  [0.59299052 0.6294259  0.23444372]]

 [[0.1823469  0.74784671 0.09939497]
  [0.35764839 0.62403419 0.20795416]
  [0.04516328 0.33769361 0.98574175]]

 [[0.7808156  0.66989807 0.71973729]
  [0.02362599 0.46083748 0.39316248]
  [0.80482911 0.23785321 0.94423292]]]


In [13]:
# Replace all odd numbers in arr with -1
# your code here
#pass
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print("Arreglo con números impares reemplazados por -1:")
print(arr)

Arreglo con números impares reemplazados por -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [14]:
# Create an array of type float
#pass
arreglo_float = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

print("Arreglo de tipo float:")
print(arreglo_float)

Arreglo de tipo float:
[1.1 2.2 3.3 4.4 5.5]


In [15]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
#pass
arreglo_1d = np.array([1, 2, 3, 4, 5, 6])
arreglo_2d = arreglo_1d.reshape(2, -1)

print("Arreglo bidimensional con 2 filas:")
print(arreglo_2d)

Arreglo bidimensional con 2 filas:
[[1 2 3]
 [4 5 6]]


In [16]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
#pass
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
valores_comunes = np.intersect1d(Z1, Z2)

print("Valores comunes entre Z1 y Z2:")
print(valores_comunes)

Valores comunes entre Z1 y Z2:
[0 3 4 5 6 9]


In [17]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
#pass
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
son_iguales = np.array_equal(A, B)

if son_iguales:
    print("Los arreglos A y B son iguales.")
else:
    print("Los arreglos A y B no son iguales.")

Los arreglos A y B no son iguales.


In [18]:
# Stack arrays a and b vertically
# your code here
#pass
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.vstack((a, b))

print("Arreglos apilados verticalmente:")
print(resultado)

Arreglos apilados verticalmente:
[[1 2 3]
 [4 5 6]]


In [19]:
# Stack the arrays a and b horizontally.
# your code here
#pass
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.hstack((a, b))

print("Arreglos apilados horizontalmente:")
print(resultado)

Arreglos apilados horizontalmente:
[1 2 3 4 5 6]


In [20]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
# pass
elementos_entre_5_y_10 = tmp[(tmp >= 5) & (tmp <= 10)]

print("Elementos entre 5 y 10 del arreglo tmp:")
print(elementos_entre_5_y_10)

Elementos entre 5 y 10 del arreglo tmp:
[ 5  6  7  8  9 10]


In [21]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
pair_max = np.vectorize(maxx)

# Example usage
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Call the pair_max function on NumPy arrays
result = pair_max(a, b)

print("Result of pair_max(a, b):")
print(result)

Result of pair_max(a, b):
[6 7 9 8 9 7 5]


In [22]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
#pass
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

arr[:, [1, 2]] = arr[:, [2, 1]]

print("Array after swapping columns 1 and 2:")
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after swapping columns 1 and 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [23]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]

random_array = np.random.uniform(5, 10, size=(5, 3))

print("2D array with random decimal numbers between 5 and 10:")
print(random_array)

2D array with random decimal numbers between 5 and 10:
[[5.30422018 7.00938443 9.67556709]
 [6.8480757  6.13131048 5.27508829]
 [8.72961593 5.42095078 6.56426448]
 [5.22459677 7.98439556 7.67961003]
 [5.25607022 9.55774029 6.64864158]]
