<a href="https://colab.research.google.com/github/Hamilton09/tareas/blob/main/Cuaderno_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [5]:
aux=np.array([1,2,3,4,5])
print(aux)
print(aux.shape)

aux2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(aux2)
print(aux2.shape)
print(type(aux2))

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
<class 'numpy.ndarray'>


In [6]:
tmp=np.zeros((4,4))
print(tmp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print("Matriz full valores del mismo numeroi")
tmp=np.full((4,4),5)
print(tmp)

Matriz full valores del mismo numeroi
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [8]:
print("Matriz diagonal")
tmp=np.eye(4,4)
print(tmp)

Matriz diagonal
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
print("Matriz de 1")
tmp=np.ones((4,4))
print(tmp)

Matriz de 1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)

Numeros randoms
[[1.50506114 2.81102412 8.88815837 1.67568401]
 [1.05264282 0.8300028  7.62440076 0.74145545]
 [3.51437195 5.95990864 5.33416722 6.5836974 ]
 [7.82529691 7.4146055  6.47394464 4.48480887]]
(4, 4)


In [11]:
print(tmp[:2,:2])

[[1.50506114 2.81102412]
 [1.05264282 0.8300028 ]]


In [12]:
print(tmp[:2,1:3])

[[2.81102412 8.88815837]
 [0.8300028  7.62440076]]


In [13]:
print(tmp[3])

[7.82529691 7.4146055  6.47394464 4.48480887]


In [14]:
print(tmp[2,2])

5.334167217017004


In [15]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)

Numeros randoms
[[8.85584409 1.21843306 0.83102329 7.73974671]
 [8.69816942 4.31128915 7.1149265  0.7045951 ]
 [1.56863619 9.95696628 2.84435999 0.95022281]
 [7.50546447 7.40442986 3.26741946 5.4167723 ]]
(4, 4)


In [16]:
mask=tmp>5
print(tmp[mask])

[8.85584409 7.73974671 8.69816942 7.1149265  9.95696628 7.50546447
 7.40442986 5.4167723 ]


In [17]:
mask=(tmp>=2)&(tmp<=4)
print(tmp[mask])

[2.84435999 3.26741946]


In [18]:
# Crear un arreglo de 4x4 con valores aleatorios enteros entre 1 y 100
arreglo = np.random.randint(1, 101, size=(4, 4))

print("Arreglo original:")
print(arreglo)

# Crear una máscara booleana para los números pares
mascara_pares = arreglo % 2 == 0

# Aplicar la máscara para seleccionar los números pares
numeros_pares = arreglo[mascara_pares]

print("Números pares:")
print(numeros_pares)

Arreglo original:
[[78 80 17 46]
 [20 73 59 18]
 [95 13 83  9]
 [65 85 17 16]]
Números pares:
[78 80 46 20 18 16]
