<a href="https://colab.research.google.com/github/Hamilton09/tareas/blob/main/NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [3]:
# Import numpy as np and see the version

# your code here
#pass
import numpy as np

# Verificar la versión de NumPy
print("Versión de NumPy:", np.__version__)

Versión de NumPy: 1.23.5


In [4]:
# Create a 1D array of numbers from 0 to 9
# your code here
#pass
import numpy as np

# Crear un array 1D con números del 0 al 9
array_1d = np.arange(10)

# Imprimir el array resultante
print(array_1d)


[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Create random vector of size 10 and replace the maximum value by 0
#pass
import numpy as np

# Crear un vector aleatorio de tamaño 10
random_vector = np.random.rand(10)

# Imprimir el vector original
print("Vector original:")
print(random_vector)

# Encontrar el índice del valor máximo
max_index = np.argmax(random_vector)

# Reemplazar el valor máximo por 0
random_vector[max_index] = 0

# Imprimir el vector después de la modificación
print("\nVector con el máximo reemplazado por 0:")
print(random_vector)


Vector original:
[0.07487834 0.09745486 0.29070985 0.54377705 0.68203273 0.17646827
 0.09539906 0.36632132 0.4993012  0.8550234 ]

Vector con el máximo reemplazado por 0:
[0.07487834 0.09745486 0.29070985 0.54377705 0.68203273 0.17646827
 0.09539906 0.36632132 0.4993012  0.        ]


In [6]:
# # Print the number 8 from the array below:
# # arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# pass
import numpy as np

# Definir la matriz
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Imprimir el número 8
print("Número 8 en la matriz:", arr[1, 2])


Número 8 en la matriz: 8


In [7]:
# # Print the numbers [3, 4, 5] from the array below:
# # arr = np.array([1,2,3,4,5,6,7])
# pass
import numpy as np

# Definir el array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los números [3, 4, 5]
print("Números [3, 4, 5] en el array:", arr[2:5])


Números [3, 4, 5] en el array: [3 4 5]


In [8]:
# # Print the last 4 numbers from the array below:
# # arr = np.array([1,2,3,4,5,6,7])
# pass
import numpy as np

# Definir el array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los últimos 4 números
print("Últimos 4 números en el array:", arr[-4:])


Últimos 4 números en el array: [4 5 6 7]


In [9]:
# # Create a 3×3 numpy array of all True’s
# # your code here
# pass
import numpy as np

# Crear una matriz de 3x3 con todos los valores True
true_matrix = np.ones((3, 3), dtype=bool)

# Imprimir la matriz resultante
print(true_matrix)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
# # Extract all odd numbers from arr
# # your code here
# pass
import numpy as np

# Definir la matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extraer los números impares
odd_numbers = arr[arr % 2 != 0]

# Imprimir los números impares
print("Números impares en la matriz:", odd_numbers)


Números impares en la matriz: [1 3 5 7 9]


In [11]:
# # Create a vector with values ranging from 10 to 49 (★☆☆)
# pass
import numpy as np

# Crear un vector con valores en el rango de 10 a 49
vector = np.arange(10, 50)

# Imprimir el vector resultante
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# # Reverse a vector (first element becomes last)
# pass
import numpy as np

# Crear un vector
vector = np.array([1, 2, 3, 4, 5])

# Invertir el vector
reversed_vector = vector[::-1]

# Imprimir el vector invertido
print("Vector original:", vector)
print("Vector invertido:", reversed_vector)


Vector original: [1 2 3 4 5]
Vector invertido: [5 4 3 2 1]


In [13]:
# #  Create a 10x10 array with random integer values and find the minimum and maximum values
# pass
import numpy as np

# Crear una matriz de 10x10 con valores enteros aleatorios
random_matrix = np.random.randint(low=1, high=100, size=(10, 10))

# Imprimir la matriz
print("Matriz aleatoria:")
print(random_matrix)

# Encontrar el valor mínimo y máximo
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)

# Imprimir los resultados
print("\nValor mínimo:", min_value)
print("Valor máximo:", max_value)


Matriz aleatoria:
[[43 39 92 16 83 81  8 45 30 72]
 [11  5  4 51  1 32 44 68 22 26]
 [67 38 76 73 69 54 60 12 64 48]
 [62 68  4 35 30  8 85 38 32 20]
 [ 4 21 88 33  8 98 22 65  1 64]
 [21 67 67 15 62 67 53 85 81 83]
 [65 45 49 28 55 96 65 68 65 43]
 [19 72  1 24 46 61 56 24 70 62]
 [93 99  2 99 88 21 11 22 92 48]
 [36 93 37  3 24 46 30 88 33  5]]

Valor mínimo: 1
Valor máximo: 99


In [14]:
# # Create a 3x3x3 array with random values
# pass
import numpy as np

# Crear una matriz tridimensional (3x3x3) con valores aleatorios
random_3d_array = np.random.rand(3, 3, 3)

# Imprimir la matriz tridimensional
print("Matriz tridimensional con valores aleatorios:")
print(random_3d_array)


Matriz tridimensional con valores aleatorios:
[[[0.86126976 0.09762595 0.11954385]
  [0.85595118 0.94065492 0.89914395]
  [0.13230066 0.54926999 0.75319396]]

 [[0.21122017 0.45339971 0.45295429]
  [0.02432861 0.07146527 0.16877773]
  [0.06290251 0.71238341 0.53017548]]

 [[0.61264029 0.74041816 0.72108441]
  [0.25977181 0.37226708 0.7179199 ]
  [0.17846605 0.32217157 0.60126556]]]


In [15]:
# # Replace all odd numbers in arr with -1
# # your code here
# pass
import numpy as np

# Definir el array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Crear una máscara para los números impares
mask = arr % 2 != 0

# Reemplazar los números impares con -1
arr[mask] = -1

# Imprimir el array después de la modificación
print("Array después de reemplazar los impares con -1:")
print(arr)


Array después de reemplazar los impares con -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [16]:
# # Create an array of type float
# pass
import numpy as np

# Crear un array de tipo float
float_array = np.array([1.0, 2.5, 3.7], dtype=float)

# Imprimir el array y su tipo de dato
print("Array de tipo float:", float_array)
print("Tipo de dato del array:", float_array.dtype)


Array de tipo float: [1.  2.5 3.7]
Tipo de dato del array: float64


In [17]:
# # Convert a 1D array to a 2D array with 2 rows
# # your code here
# pass
import numpy as np

# Crear un array unidimensional
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Convertir a un array bidimensional con 2 filas
array_2d = array_1d.reshape(2, -1)

# Imprimir el array bidimensional resultante
print("Array bidimensional con 2 filas:")
print(array_2d)


Array bidimensional con 2 filas:
[[1 2 3 4]
 [5 6 7 8]]


In [18]:
# # How to find common values between two arrays?

# # Z1 = np.random.randint(0,10,10)
# # Z2 = np.random.randint(0,10,10)
# pass
import numpy as np

# Crear dos arrays aleatorios
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Encontrar los valores comunes
common_values = np.intersect1d(Z1, Z2)

# Imprimir los resultados
print("Array 1:", Z1)
print("Array 2:", Z2)
print("Valores comunes:", common_values)


Array 1: [1 0 7 6 4 3 2 8 2 7]
Array 2: [1 1 3 2 3 5 1 0 6 4]
Valores comunes: [0 1 2 3 4 6]


In [19]:
# #  Consider two random array A and B, check if they are equal


# # A = np.random.randint(0,2,5)
# # B = np.random.randint(0,2,5)

# pass
import numpy as np

# Crear dos arrays aleatorios
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Verificar si los arrays son iguales
are_equal = np.array_equal(A, B)

# Imprimir el resultado
print("Array A:", A)
print("Array B:", B)
print("¿Los arrays son iguales?", are_equal)


Array A: [1 1 0 1 0]
Array B: [1 0 0 0 0]
¿Los arrays son iguales? False


In [20]:
# # Stack arrays a and b vertically
# # your code here
# pass
import numpy as np

# Crear dos arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apilar los arrays verticalmente
stacked_array = np.vstack((a, b))

# Imprimir el resultado
print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nArrays apilados verticalmente:")
print(stacked_array)


Array a:
[1 2 3]

Array b:
[4 5 6]

Arrays apilados verticalmente:
[[1 2 3]
 [4 5 6]]


In [21]:
# # Stack the arrays a and b horizontally.
# # your code here
# pass
import numpy as np

# Crear dos arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apilar los arrays horizontalmente
stacked_array = np.hstack((a, b))

# Imprimir el resultado
print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nArrays apilados horizontalmente:")
print(stacked_array)


Array a:
[1 2 3]

Array b:
[4 5 6]

Arrays apilados horizontalmente:
[1 2 3 4 5 6]


In [22]:
# # Get all items between 5 and 10 from array tmp.
# # your code here
# import numpy as np
# tmp = np.arange(15)
# # pass
import numpy as np

tmp = np.arange(15)

# Obtener los elementos entre 5 y 10
result = tmp[(tmp >= 5) & (tmp <= 10)]

# Imprimir el resultado
print("Elementos entre 5 y 10:", result)


Elementos entre 5 y 10: [ 5  6  7  8  9 10]


In [23]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def pair_max(x, y):
    """Get the maximum of two items"""
    return np.maximum(x, y)

# Example usage
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)


[6 7 9 8 9 7 5]


In [24]:
# # Swap columns 1 and 2 in the array arr.
# # Hint
# # Desired Output:
# # [[0 2 1]
# #  [3 5 4]
# #  [6 8 7]]


# arr = np.arange(9).reshape(3,3)
# print(arr)
# # your code here
# pass
import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nArray after swapping columns 1 and 2:")
print(arr)


Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Array after swapping columns 1 and 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [25]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]
import numpy as np

# Create a 2D array of shape 5x3 with random decimal numbers between 5 and 10
random_array = np.random.uniform(5, 10, size=(5, 3))

# Print the result
print(random_array)



[[5.04084822 5.74046493 9.65999382]
 [8.36090816 7.38877013 9.71732648]
 [5.10442684 5.34956609 5.41903085]
 [6.13327785 6.95459769 9.97547369]
 [5.80630858 7.54337293 5.13323565]]
